apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-clusterrole
  namespace: webapps
rules:
  - apiGroups:
        - ""
        - apps
        - batch
        - policy
        - networking.k8s.io
        - coordination.k8s.io
        - discovery.k8s.io
        - rbac.authorization.k8s.io
        - admissionregistration.k8s.io
    resources: ["deployments","secrets","jobs","events","endpoints","leases","ingresses","ingresses/status","endpointslices","serviceaccounts","ingress","namespaces","nodes","pods","resourcequotas","replicasets","validatingwebhookconfigurations","replicationcontrollers","serviceaccounts","services","poddisruptionbudgets","configmaps","clusterroles","clusterrolebindings","roles","rolebindings","apps","networking.k8s.io","ingressclasses"]
    verbs: ["get", "list", "watch", "create","delete","update","patch"]
