apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: app-clurole-service-secret
  namespace: webapps
  annotations:
    kubernetes.io/service-account.name: app-clurole-service-account
